FROM --platform=linux/amd64 debian:bookworm-slim as base

WORKDIR /opt
COPY test_utils/install_cached_deps.sh .
RUN bash /opt/install_cached_deps.sh

FROM  --platform=linux/amd64 base as chef
ENV PATH="/root/.cargo/bin:$PATH"
RUN rustc -V

FROM --platform=linux/amd64 chef AS planner
WORKDIR /opt
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM --platform=linux/amd64 chef AS builder
WORKDIR /opt
COPY --from=planner /opt/recipe.json recipe.json
RUN rustup toolchain install nightly-2024-06-08-x86_64-unknown-linux-gnu
RUN cargo +nightly-2024-06-08 chef cook --recipe-path recipe.json

COPY . .

RUN  maturin build  --manifest-path py-smelt/Cargo.toml --out dist && rm -rf target/
RUN python3 -m pip install  --break-system-packages  dist/*.whl



