FROM --platform=linux/amd64 ghcr.io/pyo3/maturin as builder
WORKDIR /app
COPY . . 
RUN maturin build --interpreter python3.9 --manifest-path py-smelt/Cargo.toml --out dist
#RUN maturin build --interpreter python3.10 --manifest-path py-smelt/Cargo.toml --out dist
FROM --platform=linux/amd64  2048bees/docker-centos8-slurm:latest  as runtime
# install docker
RUN yum install -y yum-utils && yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
ARG SMELT_VERSION
RUN echo "SMELT_VERSION: $SMELT_VERSION"
COPY --from=builder /app/dist /dist
RUN alternatives --set python3 /usr/bin/python3.9
RUN pip3 install dist/pysmelt-${SMELT_VERSION}-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl && pip3 install pytest

WORKDIR /smelt_src
COPY . . 
CMD ["pytest", "slurm-pytests"]


FROM centos:centos8 as sealed_runtime

ENV PATH "/root/.pyenv/shims:/root/.pyenv/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin"

EXPOSE 6817 6818 6819 6820 3306
RUN  sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum install -y dnf-plugins-core &&  yum install -y epel-release &&  yum config-manager --set-enabled powertools
# Install common YUM dependency packages
# The IUS repo install epel-release as a dependency while also providing a newer version of Git
RUN set -ex \
    && yum -y update \
    && yum -y install \
        autoconf \
        bash-completion \
        git  \
        python39 python39-pip python39-devel  \
    && yum clean all \
    && rm -rf /var/cache/yum

ARG SMELT_VERSION
RUN echo "SMELT_VERSION: $SMELT_VERSION"
COPY --from=builder /app/dist /dist
RUN alternatives --set python3 /usr/bin/python3.9
RUN pip3 install dist/pysmelt-${SMELT_VERSION}-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl && pip3 install pytest
WORKDIR /opt
COPY . . 
CMD ["bash"]

