name: postcommit-slurm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run Docker image
        run: |
          docker build --platform linux/amd64 -f test_utils/Dockerfile.slurm_dev . --tag smeltdev
          docker run --hostname slurmctl --platform linux/amd64 smeltdev
