name: wheelbuild

on:
  push:
    branches:
      - "release-*"

permissions:
  contents: write

jobs:
  test-build-release-branch-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
        target: [x86_64]
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --manifest-path py-smelt/Cargo.toml --out dist --interpreter 3.8 --interpreter 3.9 --interpreter 3.10 --interpreter 3.11 --interpreter 3.12
          sccache: "true"
          manylinux: auto
